apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.53.0
        # --- PHẦN BỔ SUNG QUAN TRỌNG ---
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        # -----------------------------
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus/"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-storage # Gắn volume lưu trữ vào container
          mountPath: /prometheus/
        - name: prometheus-config # Gắn file config
          mountPath: /etc/prometheus/
      volumes:
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: prometheus-pvc # Sử dụng PVC đã tạo ở trên
      - name: prometheus-config
        configMap:
          name: prometheus-configmap # Cần tạo thêm ConfigMap cho prometheus